// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAGkcbKw8dQOepuMRk5KykKWGrYuI6h3_E',
    appId: '1:166108951169:web:cea8545a7324cfdc8c9380',
    messagingSenderId: '166108951169',
    projectId: 'php-dbms',
    authDomain: 'php-dbms.firebaseapp.com',
    storageBucket: 'php-dbms.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBDWU-6JuoURme5532DE1RO5bx8MgwP_eE',
    appId: '1:166108951169:android:0e6a6f1d4b3a733f8c9380',
    messagingSenderId: '166108951169',
    projectId: 'php-dbms',
    storageBucket: 'php-dbms.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDGgAboQp-f6ERGrFboYvV4AYKF5dzpGYk',
    appId: '1:166108951169:ios:0fc3c02e9329d5dc8c9380',
    messagingSenderId: '166108951169',
    projectId: 'php-dbms',
    storageBucket: 'php-dbms.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDGgAboQp-f6ERGrFboYvV4AYKF5dzpGYk',
    appId: '1:166108951169:ios:0fc3c02e9329d5dc8c9380',
    messagingSenderId: '166108951169',
    projectId: 'php-dbms',
    storageBucket: 'php-dbms.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAGkcbKw8dQOepuMRk5KykKWGrYuI6h3_E',
    appId: '1:166108951169:web:86201d45829490358c9380',
    messagingSenderId: '166108951169',
    projectId: 'php-dbms',
    authDomain: 'php-dbms.firebaseapp.com',
    storageBucket: 'php-dbms.firebasestorage.app',
  );

}